# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dr. med. Ulla Raczinski
email: u.raczinski@t-online.de
description: >
  Psychotherapie von und Beratung zu psychischen und psychosomatischen
  Krankheitsbildern wie Angst-und Panikstörungen, Depressionen, Essstörungen
  u.a.; Schwerpunkte der Praxis sind u.a.: Psychoonkologie, d.h. Psychotherapie
  bei Krebserkrankungen sowie Psychotraumatologie, d.h. Behandlungen von
  psychischen Störungen, die durch akute Traumata oder durch komplexe lang
  anhaltende Traumatisierung entstanden sind.
baseurl: ""
url: "http://www.dr-ulla-raczinski.de"
twitter_username:
github_username:

# Build settings
markdown: kramdown
theme: jekyll-theme-architect
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
